# This file serves as a directive for injected GraphQL queries
# in automated test suite code.

schema:
  - "schema/src/main/resources/schema/base.graphqls"
  - "schema/src/main/resources/schema/findJourneys.graphqls"
  - "schema/src/main/resources/schema/metadata.graphqls"
  - "schema/src/main/resources/schema/passService.graphqls"
  - "schema/src/main/resources/schema/place.graphqls"
  - "schema/src/main/resources/schema/search.graphqls"
  - "schema/src/main/resources/schema/stop.graphqls"
  - "schema/src/main/resources/schema/types.graphqls"
extensions:
  endpoints:
    # Allows us to use IntelliJ scratch files to query the server
    # when running it on localhost
    local: http://localhost:8080/dutch-railways/v1/graphql
    local-compose: http://localhost:80/dutch-railways/v1/graphql
    hosted: http://fajita-jw125.duckdns.org:80/dutch-railways/v1/graphql
