# This file serves as a directive for injected GraphQL queries
# in automated test suite code.

schema: "./**/resources/schema/*.graphqls"
extensions:
  endpoints:
    # Allows us to use IntelliJ scratch files to query the server
    # when running it on localhost
    default: http://localhost:8080/graphql
