# generated by datamodel-codegen:
#   filename:  nsapp-stations-api.yaml
#   timestamp: 2026-04-28T10:56:25+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field


class StationIdentification(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    uicCode: str = Field(..., description='Short UIC code for this station')
    uicCdCode: str | None = Field(
        None, description='Long UIC code for this station, if present'
    )
    evaCode: str | None = Field(
        None, description='EuroEVA code for this station, if present'
    )
    cdCode: float | None = Field(
        None, description='Short code that is used for price computations (MRP)'
    )
    code: str | None = Field(
        None, description='Short station code (e.g. UT for Utrecht Centraal)'
    )


class StationTypeV3(Enum):
    LOCAL_TRAIN_STATION = 'LOCAL_TRAIN_STATION'
    LOCAL_TRAIN_HUB_STATION = 'LOCAL_TRAIN_HUB_STATION'
    EXPRESS_TRAIN_STATION = 'EXPRESS_TRAIN_STATION'
    EXPRESS_TRAIN_HUB_STATION = 'EXPRESS_TRAIN_HUB_STATION'
    INTERCITY_STATION = 'INTERCITY_STATION'
    INTERCITY_HUB_STATION = 'INTERCITY_HUB_STATION'
    MEGA_STATION = 'MEGA_STATION'
    OPTIONAL_STATION = 'OPTIONAL_STATION'


class StationNames(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    long: str
    medium: str
    short: str
    festive: str | None = None
    synonyms: list[str] = Field(..., description='List of synonyms for this station')


class Coordinate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    lat: float
    lng: float


class NearbyMeLocationId(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: str
    type: str


class Track(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    spoorNummer: str


class StationTypeV2(Enum):
    STOPTREIN_STATION = 'STOPTREIN_STATION'
    KNOOPPUNT_STOPTREIN_STATION = 'KNOOPPUNT_STOPTREIN_STATION'
    SNELTREIN_STATION = 'SNELTREIN_STATION'
    KNOOPPUNT_SNELTREIN_STATION = 'KNOOPPUNT_SNELTREIN_STATION'
    INTERCITY_STATION = 'INTERCITY_STATION'
    KNOOPPUNT_INTERCITY_STATION = 'KNOOPPUNT_INTERCITY_STATION'
    MEGA_STATION = 'MEGA_STATION'
    FACULTATIEF_STATION = 'FACULTATIEF_STATION'


class StationsNamen(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    lang: str
    middel: str
    kort: str
    festive: str | None = None


class StationV2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    UICCode: str
    UICCdCode: str | None = None
    stationType: StationTypeV2
    EVACode: str | None = None
    cdCode: float | None = None
    code: str | None = None
    sporen: list[Track]
    synoniemen: list[str]
    heeftFaciliteiten: bool
    heeftVertrektijden: bool
    heeftReisassistentie: bool
    namen: StationsNamen | None = None
    land: str | None = None
    lat: float | None = None
    lng: float | None = None
    radius: float | None = None
    naderenRadius: float | None = None
    distance: float | None = None
    ingangsDatum: str | None = None
    eindDatum: str | None = None
    nearbyMeLocationId: NearbyMeLocationId | None = None


class StationsV2Response(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    payload: list[StationV2]


class V2GetParameters(BaseModel):
    q: str | None = None
    includeNonPlannableStations: bool | None = False
    countryCodes: list[str] | None = None
    limit: int | None = 10


class V2GetResponse(BaseModel):
    message: str | None = None


class V2NearestGetParameters(BaseModel):
    lat: float
    lng: float
    limit: int | None = 2
    includeNonPlannableStations: bool | None = False


class V2NearestGetResponse(BaseModel):
    message: str | None = None


class V3GetParameters(BaseModel):
    q: str | None = None
    includeNonPlannableStations: bool | None = False
    countryCodes: list[str] | None = None
    limit: int | None = 10


class V3GetResponse(BaseModel):
    message: str | None = None


class V3NearestGetParameters(BaseModel):
    lat: float
    lng: float
    limit: int | None = 2
    includeNonPlannableStations: bool | None = False


class V3NearestGetResponse(BaseModel):
    message: str | None = None


class V1StationGetParameters(BaseModel):
    uicCode: str | None = None
    uicCdCode: str | None = None


class V1StationGetResponse(BaseModel):
    message: str | None = None


class StationV3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: StationIdentification
    stationType: StationTypeV3
    names: StationNames
    location: Coordinate | None = None
    tracks: list[str] = Field(..., description='List of tracks known to this station')
    hasKnownFacilities: bool = Field(
        ..., description='Indicates whether this station has known facilities'
    )
    availableForAccessibleTravel: bool = Field(
        ...,
        description='Indicates whether this station is available for accessible travel (i.e. has travel assistance or tracks that are independently accessible)',
    )
    hasTravelAssistance: bool = Field(
        ...,
        description='Indicates that NSRA (NS Reisassistentie) is available at this station',
    )
    areTracksIndependentlyAccessible: bool = Field(
        ...,
        description='Indicates that the tracks at this station are accessible without assistance. Please note that when the train itself is not accessible without assistance, the traveller still needs assistance.',
    )
    isBorderStop: bool = Field(
        ...,
        description='Indicates whether this station is only used to mark a border between two countries',
    )
    country: str = Field(..., description='Country that this station is in')
    radius: float | None = Field(
        None,
        description='Radius around the exact location of the station where a someone is considered to be at the station',
    )
    approachingRadius: float | None = Field(
        None,
        description='Radius around a station where a train is considered to be approaching the station',
    )
    distance: float | None = Field(
        None,
        description='Distance in meters to a requested coordinate (latitude, longitude)',
    )
    startDate: str | None = Field(
        None,
        description='Start date for this station (ISO Format). If not set, the date is unknown and the station is supposed to be opened',
    )
    endDate: str | None = Field(
        None,
        description='End date for this station (ISO Format). If not set, the date is unknown and the station is supposed to be opened.',
    )
    nearbyMeLocationId: NearbyMeLocationId | None = None


class StationsV3Response(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    payload: list[StationV3]


class StationV3Response(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    payload: StationV3
