# generated by datamodel-codegen:
#   filename:  virtual-train-API.yaml
#   timestamp: 2026-04-28T10:57:03+00:00

from __future__ import annotations

from datetime import date as date_aliased
from enum import Enum

from pydantic import BaseModel


class MaterieelDeel(BaseModel):
    materieelDeel: int | None = None
    lat: float | None = None
    lng: float | None = None
    snelheid: float | None = None
    richting: float | None = None


class Trein(BaseModel):
    ritId: str | None = None
    lat: float | None = None
    lng: float | None = None
    snelheid: float | None = None
    richting: float | None = None
    horizontaleNauwkeurigheid: float | None = None
    type: str | None = None
    materieelDeelList: list[MaterieelDeel] | None = None
    treinCloneWithMaterieel: Trein | None = None


class Treinen(BaseModel):
    treinen: list[Trein] | None = None


class Afbeelding(BaseModel):
    pass


class Drukte(Enum):
    Crowdforecast_Classification_UNKNOWN = 'Crowdforecast.Classification.UNKNOWN'
    Crowdforecast_Classification_HIGH = 'Crowdforecast.Classification.HIGH'
    Crowdforecast_Classification_MEDIUM = 'Crowdforecast.Classification.MEDIUM'
    Crowdforecast_Classification_LOW = 'Crowdforecast.Classification.LOW'


class Bak(BaseModel):
    afbeelding: Afbeelding | None = None
    drukte: Drukte | None = None


class ImageData(BaseModel):
    imageUrl: str | None = None
    width: int | None = None
    height: int | None = None


class PerronVoorziening(BaseModel):
    paddingLeft: int | None = None
    width: int | None = None
    type: str | None = None
    description: str | None = None


class MaterieelType(Enum):
    DDZ_4 = 'DDZ_4'
    DDZ_6 = 'DDZ_6'
    DDZ_4SA = 'DDZ_4SA'
    SGMM_2 = 'SGMM_2'
    SGMM_3 = 'SGMM_3'
    SNG_3 = 'SNG_3'
    SNG_4 = 'SNG_4'
    SLT_4 = 'SLT_4'
    SLT_4E = 'SLT_4E'
    SLT_4ES = 'SLT_4ES'
    SLT_6 = 'SLT_6'
    SLT_6E = 'SLT_6E'
    SLT_6ES = 'SLT_6ES'
    SLT_6S = 'SLT_6S'
    FLIRT_2 = 'FLIRT_2'
    FLIRT_2_ARR = 'FLIRT_2_ARR'
    FLIRT_3_ARR = 'FLIRT_3_ARR'
    FLIRT_2_RNET = 'FLIRT_2_RNET'
    FLIRT_3 = 'FLIRT_3'
    FLIRT_3_NS = 'FLIRT_3_NS'
    FLIRT_3_FFF = 'FLIRT_3_FFF'
    FLIRT_3_BLAUWNET = 'FLIRT_3_BLAUWNET'
    FLIRT_3_KEOLIS = 'FLIRT_3_KEOLIS'
    FLIRT_4 = 'FLIRT_4'
    FLIRT_4_NS = 'FLIRT_4_NS'
    FLIRT_4_FFF = 'FLIRT_4_FFF'
    FLIRT_4_SY = 'FLIRT_4_SY'
    FLIRT_4_KEOLIS = 'FLIRT_4_KEOLIS'
    FLIRT_ABELLIO = 'FLIRT_ABELLIO'
    FLIRT_CONNEXXION = 'FLIRT_CONNEXXION'
    FLIRT_4_VL = 'FLIRT_4_VL'
    FLIRT_5_VL = 'FLIRT_5_VL'
    FLIRT_5_HGL = 'FLIRT_5_HGL'
    VIRM_4 = 'VIRM_4'
    VIRMm1_4 = 'VIRMm1_4'
    VIRMm2_4 = 'VIRMm2_4'
    VIRM_6 = 'VIRM_6'
    VIRMm1_6 = 'VIRMm1_6'
    VIRMm2_6 = 'VIRMm2_6'
    DB_REGIO_643 = 'DB_REGIO_643'
    DB_BPMZ = 'DB_BPMZ'
    DB_BER9_9 = 'DB_BER9_9'
    DB_AVMZ = 'DB_AVMZ'
    DB_B15 = 'DB_B15'
    OEBB_BMZ = 'OEBB_BMZ'
    MS80M3 = 'MS80M3'
    MS75_4 = 'MS75_4'
    DDM1_4DDM = 'DDM1_4DDM'
    ICR_GV1_9_B10 = 'ICR_GV1_9_B10'
    ICR_GV2_9_B10 = 'ICR_GV2_9_B10'
    ICR_BNL_6_B10 = 'ICR_BNL_6_B10'
    ICR_BNN_6_B10 = 'ICR_BNN_6_B10'
    ICR_HSL_6_B10 = 'ICR_HSL_6_B10'
    ICR_7 = 'ICR_7'
    SW6_25KV_2_6 = 'SW6_25KV_2_6'
    SW7_25KV_2_7 = 'SW7_25KV_2_7'
    SW9_25KV_2_9 = 'SW9_25KV_2_9'
    ELOC_1700 = 'ELOC_1700'
    ELOC_TR25 = 'ELOC_TR25'
    ELOC_TRBE = 'ELOC_TRBE'
    ELOC_TRAX = 'ELOC_TRAX'
    CPROTOS_2 = 'CPROTOS_2'
    DM90_2 = 'DM90_2'
    DDAR_3 = 'DDAR_3'
    EUROSTAR = 'EUROSTAR'
    THALYS = 'THALYS'
    TGV_PB = 'TGV_PB'
    ICE = 'ICE'
    ICE_3 = 'ICE_3'
    ICE_3NEO = 'ICE_3NEO'
    MAT64 = 'MAT64'
    GTW26 = 'GTW26'
    GTWE26 = 'GTWE26'
    GTW28 = 'GTW28'
    GTWE28 = 'GTWE28'
    GTWE26_VECHTDAL = 'GTWE26_VECHTDAL'
    GTWE28_VETCHDAL = 'GTWE28_VETCHDAL'
    GTW26_LIMBURG = 'GTW26_LIMBURG'
    GTW28_LIMBURG = 'GTW28_LIMBURG'
    GTWE26_LIMBURG = 'GTWE26_LIMBURG'
    GTWE28_LIMBURG = 'GTWE28_LIMBURG'
    GTW26_ARRIVA = 'GTW26_ARRIVA'
    GTW28_ARRIVA = 'GTW28_ARRIVA'
    GTW26_NOORD = 'GTW26_NOORD'
    GTW28_NOORD = 'GTW28_NOORD'
    GTWE26_ARRIVA = 'GTWE26_ARRIVA'
    GTWE28_ARRIVA = 'GTWE28_ARRIVA'
    GTW26_VEOLIA = 'GTW26_VEOLIA'
    GTW28_VEOLIA = 'GTW28_VEOLIA'
    GTWE26_VEOLIA = 'GTWE26_VEOLIA'
    GTWE28_VEOLIA = 'GTWE28_VEOLIA'
    GTW8_BRENG = 'GTW8_BRENG'
    GTW26_QBUZZ = 'GTW26_QBUZZ'
    GTWE28_QBUZZ = 'GTWE28_QBUZZ'
    LINT2 = 'LINT2'
    LINT2_ARRIVA = 'LINT2_ARRIVA'
    LINT2_VEOLIA = 'LINT2_VEOLIA'
    LINT2_SYNTUS = 'LINT2_SYNTUS'
    LINT2_KEOLIS = 'LINT2_KEOLIS'
    ICM3 = 'ICM3'
    ICM4 = 'ICM4'
    ICNG5 = 'ICNG5'
    ICNG8 = 'ICNG8'
    WINK_ARRIVA = 'WINK_ARRIVA'
    UNKNOWN = 'UNKNOWN'


class FaciliteitenEnum(Enum):
    TOILET = 'TOILET'
    STILTE = 'STILTE'
    STROOM = 'STROOM'
    TOEGANKELIJK = 'TOEGANKELIJK'
    FIETS = 'FIETS'
    WIFI = 'WIFI'
    BISTRO = 'BISTRO'


class TreinDrukte(BaseModel):
    pass


class Bron(Enum):
    DVS = 'DVS'
    KV6 = 'KV6'
    OBIS = 'OBIS'
    DAGPLAN = 'DAGPLAN'
    NMBS = 'NMBS'


class Rijrichting(Enum):
    LINKS = 'LINKS'
    RECHTS = 'RECHTS'


class ZitplaatsInformatie(BaseModel):
    staanplaatsEersteKlas: int | None = None
    staanplaatsTweedeKlas: int | None = None
    zitplaatsEersteKlas: int | None = None
    zitplaatsTweedeKlas: int | None = None
    klapstoelEersteKlas: int | None = None
    klapstoelTweedeKlas: int | None = None


class Classification(Enum):
    Crowdforecast_Classification_UNKNOWN = 'Crowdforecast.Classification.UNKNOWN'
    Crowdforecast_Classification_HIGH = 'Crowdforecast.Classification.HIGH'
    Crowdforecast_Classification_MEDIUM = 'Crowdforecast.Classification.MEDIUM'
    Crowdforecast_Classification_LOW = 'Crowdforecast.Classification.LOW'


class Crowdforecast(BaseModel):
    trainNumber: int | None = None
    stationUic: str | None = None
    date: date_aliased | None = None
    classification: Classification | None = None


class Type(Enum):
    BAKBORD = 'BAKBORD'
    BAKBORDEINDE = 'BAKBORDEINDE'
    LETTERBORD = 'LETTERBORD'
    LIFT = 'LIFT'
    TRAP = 'TRAP'
    BANK = 'BANK'
    AFVAL = 'AFVAL'
    KAP = 'KAP'
    CTA = 'CTA'
    ROLTRAP = 'ROLTRAP'
    PERRONEINDE = 'PERRONEINDE'
    PERRONBEGIN = 'PERRONBEGIN'
    JUK = 'JUK'
    SEIN = 'SEIN'
    ANDERS = 'ANDERS'


class PlatformItem(BaseModel):
    position: float | None = None
    type: Type | None = None
    platformLetter: str | None = None
    bakBord: int | None = None
    bakBordKrom: int | None = None
    fase: str | None = None
    description: str | None = None
    bakBordKromOrElseBakBord: int | None = None


class V1ImagesImageGetParameters(BaseModel):
    image: str


class V1ImagesMaterieelImageGetParameters(BaseModel):
    materieel: str
    image: str


class Features(Enum):
    bus = 'bus'
    materieel = 'materieel'
    trein = 'trein'


class VehicleGetParameters(BaseModel):
    lat: float | None = 0
    lng: float | None = 0
    radius: int | None = None
    limit: int | None = None
    route: int | None = None
    features: Features | None = None


class V1PlatformStationPlatformGetParameters(BaseModel):
    station: str
    platform: str


class V1PrognoseRitnummerGetParameters(BaseModel):
    ritnummer: int


class V1RitnummerMaterieelnummerGetParameters(BaseModel):
    materieelnummer: int


class Features1(Enum):
    zitplaats = 'zitplaats'
    platformitems = 'platformitems'
    cta = 'cta'
    drukte = 'drukte'
    druktev2 = 'druktev2'


class V1TreinGetParameters(BaseModel):
    ids: str | None = None
    stations: str | None = None
    features: Features1 | None = None
    dateTime: str | None = None
    all: bool | None = None


class Features2(Enum):
    zitplaats = 'zitplaats'
    platformitems = 'platformitems'
    cta = 'cta'
    drukte = 'drukte'


class V1TreinRitnummerGetParameters(BaseModel):
    ritnummer: int
    features: Features2 | None = None
    dateTime: str | None = None


class V1TreinRitnummerStationscodeGetParameters(BaseModel):
    ritnummer: int
    stationscode: str
    features: Features2 | None = None
    dateTime: str | None = None


class Features4(Enum):
    bus = 'bus'
    materieel = 'materieel'
    trein = 'trein'


class ApiVehicleGetParameters(BaseModel):
    lat: float | None = 0
    lng: float | None = 0
    radius: int | None = None
    limit: int | None = None
    route: int | None = None
    features: Features4 | None = None


class Features5(Enum):
    zitplaats = 'zitplaats'
    platformitems = 'platformitems'
    cta = 'cta'
    drukte = 'drukte'


class ApiV1TreinRitnummerStationscodeGetParameters(BaseModel):
    ritnummer: int
    stationscode: str
    features: Features5 | None = None
    dateTime: str | None = None


class ApiV1TreinRitnummerGetParameters(BaseModel):
    ritnummer: int
    features: Features5 | None = None
    dateTime: str | None = None


class Features7(Enum):
    zitplaats = 'zitplaats'
    platformitems = 'platformitems'
    cta = 'cta'
    drukte = 'drukte'
    druktev2 = 'druktev2'


class ApiV1TreinGetParameters(BaseModel):
    ids: str | None = None
    stations: str | None = None
    features: Features7 | None = None
    dateTime: str | None = None
    all: bool | None = None


class ApiV1RitnummerMaterieelnummerGetParameters(BaseModel):
    materieelnummer: int


class ApiV1PrognoseRitnummerGetParameters(BaseModel):
    ritnummer: int


class ApiV1PlatformStationPlatformGetParameters(BaseModel):
    station: str
    platform: str


class ApiV1ImagesImageGetParameters(BaseModel):
    image: str


class ApiV1ImagesMaterieelImageGetParameters(BaseModel):
    materieel: str
    image: str


class TreinDeel(BaseModel):
    materieelType: MaterieelType | None = None
    drukteSVGPath: str | None = None
    materieelnummer: int | None = None
    type: str | None = None
    faciliteiten: list[FaciliteitenEnum] | None = None
    afbeelding: str | None = None
    eindbestemming: str | None = None
    bakken: list[Bak] | None = None
    afbeeldingsSpecs: ImageData | None = None
    zitplaatsInfo: ZitplaatsInformatie | None = None


class TreinInformatie(BaseModel):
    crowdInfoResponse: str | None = None
    crowdInfoRequest: str | None = None
    bron: Bron | None = None
    ritnummer: int | None = None
    station: str | None = None
    type: str | None = None
    vervoerder: str | None = None
    spoor: str | None = None
    materieeldelen: list[TreinDeel] | None = None
    geplandeMaterieeldelen: list[TreinDeel] | None = None
    lengte: int | None = None
    lengteInMeters: int | None = None
    lengteInPixels: int | None = None
    geplandeLengte: int | None = None
    perronVoorzieningen: list[PerronVoorziening] | None = None
    bakbord: int | None = None
    rijrichting: Rijrichting | None = None
    drukteVoorspelling: TreinDrukte | None = None
    treinDelen: list[TreinDeel] | None = None


class PlatformDirection(BaseModel):
    directionalPlatformItems: list[PlatformItem] | None = None
    bakBordEinde: PlatformItem | None = None
    sein: PlatformItem | None = None
    juk: PlatformItem | None = None


class PlatformGroup(BaseModel):
    station: str | None = None
    platform: str | None = None
    directionFromLeftToRight: str | None = None
    platformItems: list[PlatformItem] | None = None
    platformDirections: dict[str, PlatformDirection] | None = None
    perronEinde: PlatformItem | None = None
    perronBegin: PlatformItem | None = None


Trein.model_rebuild()
