[versions]
kotlin = "2.4.+"
spring-boot = "4.1.+"
hibernate-search = "8.4.+"
proj4j = "1.4.+"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }

[libraries]

spring-boot-bom = { group = "org.springframework.boot", name = "spring-boot-dependencies", version.ref = "spring-boot" }

kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version = "0.8.+" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version = "1.11.+" }
kotlinx-coroutines-reactor = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-reactor", version = "1.11.+" }
kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version = "1.11.+" }

kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params" }

hibernate-spatial = { group = "org.hibernate.orm", name = "hibernate-spatial", version = "7.4.+" }
spring-boot-starter-data-jpa = { group = "org.springframework.boot", name = "spring-boot-starter-data-jpa", version.ref = "spring-boot" }
postgresql = { module = "org.postgresql:postgresql", version = "42.7.+" }
geolatte-geom = { module = "org.geolatte:geolatte-geom", version = "1.11" }
proj4j = { module = "org.locationtech.proj4j:proj4j", version.ref = "proj4j" }
proj4j-epsg = { module = "org.locationtech.proj4j:proj4j-epsg", version.ref = "proj4j" }

hibernate-search-mapper-orm = { group = "org.hibernate.search", name = "hibernate-search-mapper-orm", version.ref = "hibernate-search" }
hibernate-search-backend-lucene = { group = "org.hibernate.search", name = "hibernate-search-backend-lucene", version.ref = "hibernate-search" }

spring-boot-starter-graphql = { group = "org.springframework.boot", name = "spring-boot-starter-graphql", version.ref = "spring-boot" }
spring-boot-starter-webmvc = { group = "org.springframework.boot", name = "spring-boot-starter-webmvc", version.ref = "spring-boot" }
graphql-java-extended-scalars = { group = "com.graphql-java", name = "graphql-java-extended-scalars", version = "24.+" }
jackson-kotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version = "2.18.+" }
jackson = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version = "2.21.+" }
spring-boot-starter-kotlinx-serialization = { group = "org.springframework.boot", name = "spring-boot-starter-kotlinx-serialization-json", version.ref = "spring-boot" }

spring-boot-webtestclient = { group = "org.springframework.boot", name = "spring-boot-webtestclient", version.ref = "spring-boot" }
spring-boot-data-jpa-test = { group = "org.springframework.boot", name = "spring-boot-data-jpa-test", version.ref = "spring-boot" }
spring-boot-graphql-test = { group = "org.springframework.boot", name = "spring-boot-graphql-test", version.ref = "spring-boot" }
spring-boot-webmvc-test = { group = "org.springframework.boot", name = "spring-boot-webmvc-test", version.ref = "spring-boot" }
springmockk = { group = "com.ninja-squad", name = "springmockk", version = "5.0.+" }

[bundles]
hibernate-search = ["hibernate-search-mapper-orm", "hibernate-search-backend-lucene"]
proj4j = ["proj4j", "proj4j-epsg"]
test-junit = ["kotlin-test", "junit-platform-launcher", "junit-jupiter-params"]