[versions]
kotlin = "2.4.10"
spring-boot = "4.1.0"
spring = "7.4.1.Final"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.7" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }

[libraries]
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
kotlin-test-junit5 = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit5", version.ref = "kotlin" }
kotlin-build-tools = { group = "org.jetbrains.kotlin", name = "kotlin-build-tools-impl", version.ref = "kotlin" }

kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version = "0.8.0" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core" }
kotlinx-coroutines-reactor = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-reactor" }

junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params" }

hibernate-spatial = { module = "org.hibernate.orm:hibernate-spatial", version.ref = "spring" }
spring-boot-starter-data-jpa = { group = "org.springframework.boot", name = "spring-boot-starter-data-jpa", version.ref = "spring-boot" }
postgresql = { module = "org.postgresql:postgresql", version = "42.7.13" }
geolatte-geom = { module = "org.geolatte:geolatte-geom", version = "1.12" }

spring-boot-starter-graphql = { group = "org.springframework.boot", name = "spring-boot-starter-graphql", version.ref = "spring-boot" }
spring-boot-starter-webmvc = { group = "org.springframework.boot", name = "spring-boot-starter-webmvc", version.ref = "spring-boot" }
graphql-java-extended-scalars = { group = "com.graphql-java", name = "graphql-java-extended-scalars", version = "24.0" }

spring-boot-webtestclient = { group = "org.springframework.boot", name = "spring-boot-webtestclient", version.ref = "spring-boot" }
spring-boot-data-jpa-test = { group = "org.springframework.boot", name = "spring-boot-data-jpa-test", version.ref = "spring-boot" }
spring-boot-graphql-test = { group = "org.springframework.boot", name = "spring-boot-graphql-test", version.ref = "spring-boot" }
spring-boot-webmvc-test = { group = "org.springframework.boot", name = "spring-boot-webmvc-test", version.ref = "spring-boot" }
springmockk = { group = "com.ninja-squad", name = "springmockk", version = "5.0.1" }
