extend type Query {
    searchQuery(first: Int = null, request: SearchRequest!): SearchResults
    searchLoadMore(next: Int = null, cursor: ID): SearchResults
}

input SearchRequest {
    anyLike: String = null
    nameLike: String = null
    near: InputGeoRect = null
}

type SearchResults {
    results: [SearchResultNode]
    pageInfo: PageInfo!
}

type SearchResultNode {
    passService: PassService
    area: Area
    station: Station
}

type PageInfo {
    cursor: ID
    hasNextPage: Boolean!
}
