# Includes offset
scalar DateTime @specifiedBy(url:"https://scalars.graphql.org/andimarek/date-time.html")

union GeographicGeometry = GeoCoords | GeoLinearRing | GeoMultiPolygon

type GeoCoords {
    latitude: Float!
    longitude: Float!
}

type GeoLinearRing {
    points: [GeoCoords]! # A portion of the coordinates can be dropped without issue; allow null
}

type GeoPolygon {
    rings: [GeoLinearRing]!
}

type GeoMultiPolygon {
    polygons: [GeoPolygon]!
}

input InputGeoCoords {
    latitude: Float!
    longitude: Float!
}

input InputGeoRect {
    northwest: InputGeoCoords
    southeast: InputGeoCoords
}
