package com.jeffreyalanwang.dutchrailways.backend.routeQuery.impl.raptor

import com.jeffreyalanwang.dutchrailways.backend.routeQuery.RangeRouteQueryStrategy
import com.jeffreyalanwang.dutchrailways.backend.routeQuery.finiteAndLt
import com.jeffreyalanwang.dutchrailways.backend.routeQuery.model.internal.graph.GraphAttribute
import com.jeffreyalanwang.dutchrailways.backend.routeQuery.model.internal.graph.StationId
import com.jeffreyalanwang.dutchrailways.backend.routeQuery.model.internal.graph.TransitGraph
import com.jeffreyalanwang.dutchrailways.backend.routeQuery.model.internal.obj.Journey
import kotlin.time.Instant

object RRaptor: RangeRouteQueryStrategy() {

    context(graph: TransitGraph)
    override fun invoke(
        origin: StationId,
        destination: StationId,
        timeRange: ClosedRange<Instant>,
    ) = rRaptor(origin, destination, timeRange)

}

/**
 * Range RAPTOR algorithm.
 *
 * This is a modification of RAPTOR, which returns all possible journeys
 * that take place within the given time range.
 *
 * It drops any journeys that are *strictly dominated* by another in the
 * solution set, i.e., leave at an earlier time but also arrive at a later time.
 *
 * See: https://www.microsoft.com/en-us/research/wp-content/uploads/2012/01/raptor_alenex.pdf
 *
 * @return  A list of all possible journeys that take place within the given
 *          time range, in order of depart time; empty if the journey is impossible.
 * @see raptor
 */
context(graph: TransitGraph)
internal fun rRaptor(
    origin: StationId,
    destination: StationId,
    timeRange: ClosedRange<Instant>,
): List<Journey> {
    if (origin == destination) return listOf(Journey(emptyList(), destination))

    val departTimes =
        graph[origin].trips
            .mapNotNull { graph[it].departTimeAt(origin) } // trip does not terminate at origin
            .filter { it in timeRange }

    // Run RAPTOR on possible departure times from latest to earliest
    val solutions = buildList {

        // Persist labels between parallel rounds `k` within [raptorRound].
        val labelsByK = mutableListOf(
            GraphAttribute.new<StationId, Instant?> { null }
        )
        var bestTargetAnyDepart: Instant? = null

        for (departTime in departTimes.sortedDescending()) {

            var k = 0
            var prevMarked = setOf(origin)
            val parentStationsByK = mutableListOf< GraphAttribute<StationId, StationId?> >()
            labelsByK.first()[origin] = departTime

            while (true.also { k++ }) {

                // We cannot use local pruning; in other words, while searching
                // from departure time `departTimes[i]`, round `k` may not
                // overwrite the array of labels generated by round `k - 1`.
                //
                // However, we can overwrite the array of labels generated by
                // round `k` from the previously searched departure time
                // `departTimes[i + 1]`.
                val labels =
                    labelsByK.getOrNull(k)
                        ?.apply {
                            // Provide the labels from the previous departure time,
                            // but merge with the labels from the previous round
                            // of processing our current departure time.
                            replaceIf(from = labelsByK[k - 1]) { toReplace, replaceBy ->
                                replaceBy finiteAndLt toReplace
                            }
                        }
                        ?: labelsByK[k - 1].let {
                            // We are the first departure time to require `k` rounds,
                            // so just initialize with the labels from round `k - 1`.
                            it.copy().also { labelsByK.add(it) }
                        }

                val results = raptorRound(
                    labels = labels, // gets modified as side effect
                    prevMarkedStations = prevMarked,
                    bestTargetTime = labels[destination],
                )

                // Here, a station is [marked] if it has improved
                // from both round `k - 1` for this departure time
                // *and* round `k` for the previous departure time.
                if (results.marked.none()) break // move on to the next-earliest departure time

                prevMarked = results.marked
                parentStationsByK.add(results.parentStations)
            }

            val bestTargetCurrDepart = labelsByK.last()[destination] // null (infinity) if no improved solution at this depart time
            if (bestTargetCurrDepart finiteAndLt bestTargetAnyDepart) {
                // The most-recently added journey has the earliest departure,
                // so in order for it to have been added, it must also have the
                // earliest arrival (otherwise it would have been dominated).
                //
                // Inside this if statement, we know that we are not equivalent
                // to an existing journey, and that we are not dominated
                // (even though we leave earlier).
                bestTargetAnyDepart = bestTargetCurrDepart

                // Non-null because of the `if` check above.
                val journeys = reconstructJourney(
                    destination,
                    labelsByK,
                    parentStationsByK
                )
                addAll(journeys)
            }

        }
    }

    return solutions.reversed()
}