# CAUTION: MODIFIED AFTER DATAMODEL-CODEGEN (SEE INLINE COMMENTS)
# generated by datamodel-codegen:
#   filename:  reisinformatie-api.yaml
#   timestamp: 2026-04-28T10:56:45+00:00

from __future__ import annotations

from datetime import date as date_aliased
from enum import Enum
from typing import Any, Literal

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field, RootModel, constr


class ArrivalStatus(Enum):
    ON_STATION = 'ON_STATION'
    INCOMING = 'INCOMING'
    DEPARTED = 'DEPARTED'
    UNKNOWN = 'UNKNOWN'


class CrowdForecast(Enum):
    UNKNOWN = 'UNKNOWN'
    LOW = 'LOW'
    MEDIUM = 'MEDIUM'
    HIGH = 'HIGH'


class ShorterStockClassification(Enum):
    BUSY = 'BUSY'
    EXTRA_BUSY = 'EXTRA_BUSY'


class Type(Enum):
    CALAMITY = 'CALAMITY'
    DISRUPTION = 'DISRUPTION'
    MAINTENANCE = 'MAINTENANCE'


class BaseDisruption(BaseModel):
    id: str
    isActive: bool
    title: str
    topic: str | None = None
    type: Type


class ButtonPositie(Enum):
    boven = 'boven'
    onder = 'onder'
    beide = 'beide'


class Type1(Enum):
    informatie = 'informatie'
    waarschuwing = 'waarschuwing'


class Type2(Enum):
    button__primary = 'button--primary'
    button__secondary = 'button--secondary'
    button__buy = 'button--buy'
    button__print = 'button--print'


class CallToActionButton(BaseModel):
    callToAction: str | None = None
    type: Type2 | None = None
    url: str | None = None
    voorleestitel: str | None = None


class CheckinStep(BaseModel):
    duration: int
    type: str


class Classification(Enum):
    UNKNOWN = 'UNKNOWN'
    LOW = 'LOW'
    MEDIUM = 'MEDIUM'
    HIGH = 'HIGH'


class CoachCrowdForecast(BaseModel):
    classification: Classification
    paddingLeft: int
    width: int


class Coordinate(BaseModel):
    lat: float
    lng: float


class DepartureStatus(Enum):
    ON_STATION = 'ON_STATION'
    INCOMING = 'INCOMING'
    DEPARTED = 'DEPARTED'
    UNKNOWN = 'UNKNOWN'


class DownloadFile(BaseModel):
    lastModified: int | None = None
    length: int | None = None
    mimeType: str | None = None
    url: str | None = None


class Eco(BaseModel):
    co2kg: float


class Reason(Enum):
    UNKNOWN_PRICE = 'UNKNOWN_PRICE'
    TOO_MANY_SEPARATE_PARTS = 'TOO_MANY_SEPARATE_PARTS'
    TOO_FAR_IN_PAST = 'TOO_FAR_IN_PAST'
    TOO_FAR_IN_FUTURE = 'TOO_FAR_IN_FUTURE'
    STATION_NOT_OPEN_YET = 'STATION_NOT_OPEN_YET'
    TRIP_IS_NOT_DOMESTIC = 'TRIP_IS_NOT_DOMESTIC'
    VIA_STATION_REQUESTED = 'VIA_STATION_REQUESTED'
    NO_TRAIN_LEGS_IN_TRIP = 'NO_TRAIN_LEGS_IN_TRIP'
    NON_CONTINUOUS_TRAIN_LEGS = 'NON_CONTINUOUS_TRAIN_LEGS'


class EticketNotBuyableReason(BaseModel):
    description: str | None = None
    reason: Reason


class ProductType(Enum):
    TRAIN = 'TRAIN'
    BUS = 'BUS'
    TRAM = 'TRAM'
    METRO = 'METRO'
    FERRY = 'FERRY'
    WALK = 'WALK'
    BIKE = 'BIKE'
    CAR = 'CAR'
    TAXI = 'TAXI'
    SHARED_MODALITY = 'SHARED_MODALITY'
    UNKNOWN = 'UNKNOWN'


class FareLegStop(BaseModel):
    name: str | None = None
    varCode: int


class FareRoute(BaseModel):
    destination: FareLegStop
    origin: FareLegStop
    routeId: str | None = None


class Type3(Enum):
    BTM = 'BTM'
    TRAIN_XML = 'TRAIN_XML'


class Status(Enum):
    REGISTRATION_POSSIBLE = 'REGISTRATION_POSSIBLE'
    NOT_AVAILABLE = 'NOT_AVAILABLE'
    DATE_IN_PAST = 'DATE_IN_PAST'
    DATE_TOO_FAR_FUTURE = 'DATE_TOO_FAR_FUTURE'
    NOT_NECESSARY_OTHER_OPERATOR = 'NOT_NECESSARY_OTHER_OPERATOR'
    UNKNOWN = 'UNKNOWN'


class Kind(Enum):
    DEPARTURE = 'DEPARTURE'
    ARRIVAL = 'ARRIVAL'
    TRANSFER = 'TRANSFER'


class Status1(Enum):
    ORIGIN = 'ORIGIN'
    SPLIT = 'SPLIT'
    STOP = 'STOP'
    PASSING = 'PASSING'
    COMBINE = 'COMBINE'
    DESTINATION = 'DESTINATION'
    STOP_CHANGED_ORIGIN = 'STOP_CHANGED_ORIGIN'
    STOP_CHANGED_DESTINATION = 'STOP_CHANGED_DESTINATION'


class SalesOptionType(Enum):
    NS_DEAL_DISCOUNT = 'NS_DEAL_DISCOUNT'


class LabelListItem(BaseModel):
    label: str
    salesOptionType: SalesOptionType | None = None
    stickerType: str


class TravelType(Enum):
    PUBLIC_TRANSIT = 'PUBLIC_TRANSIT'
    WALK = 'WALK'
    TRANSFER = 'TRANSFER'
    BIKE = 'BIKE'
    CAR = 'CAR'
    KISS = 'KISS'
    TAXI = 'TAXI'
    UNKNOWN = 'UNKNOWN'


class Link(BaseModel):
    uri: str


class LocalizedErrorDetail(BaseModel):
    arguments: list[dict[str, Any]]
    lang: str
    message: str
    type: str


class MeetingPointDetails(BaseModel):
    minutesBefore: int
    name: str


class Phase(Enum):
    PHASE_1A = 'PHASE_1A'
    PHASE_1B = 'PHASE_1B'
    PHASE_2 = 'PHASE_2'
    PHASE_3 = 'PHASE_3'
    PHASE_4 = 'PHASE_4'
    PHASE_5 = 'PHASE_5'


class Type4(Enum):
    MAINTENANCE = 'MAINTENANCE'
    DISRUPTION = 'DISRUPTION'
    SHORTENED = 'SHORTENED'


class NearbyMeLocationId(BaseModel):
    type: str
    value: str


class NesIcon(BaseModel):
    backgroundColor: str | None = None
    color: str
    icon: str


class NesLineStyles(BaseModel):
    dashed: bool


class Scope(Enum):
    LEG_LINE = 'LEG_LINE'
    ENTIRE_LEG = 'ENTIRE_LEG'


class NesTextStyles(BaseModel):
    bold: bool
    strikethrough: bool


class Category(Enum):
    PLATFORM_INFORMATION = 'PLATFORM_INFORMATION'
    OVERCHECK_INSTRUCTION = 'OVERCHECK_INSTRUCTION'
    UNKNOWN = 'UNKNOWN'


class NoteType(Enum):
    UNKNOWN = 'UNKNOWN'
    ATTRIBUTE = 'ATTRIBUTE'
    INFOTEXT = 'INFOTEXT'
    REALTIME = 'REALTIME'
    TICKET = 'TICKET'
    HINT = 'HINT'


class NsiLink(BaseModel):
    showInternationalBanner: bool = Field(
        ..., description='Whether to display an NS International banner'
    )
    url: str = Field(
        ..., description='NSI journeyplanner url with pre-filled locations and time'
    )


class PlatformFeature(BaseModel):
    description: str
    paddingLeft: int
    type: str
    width: int


class TravelClass(Enum):
    FIRST_CLASS = 'FIRST_CLASS'
    SECOND_CLASS = 'SECOND_CLASS'


class TravelDiscount(Enum):
    NO_DISCOUNT = 'NO_DISCOUNT'
    DISCOUNT_20 = 'DISCOUNT_20'
    DISCOUNT_40 = 'DISCOUNT_40'
    NO_CHARGE = 'NO_CHARGE'


class TravelProduct(Enum):
    OVCHIPKAART_ENKELE_REIS = 'OVCHIPKAART_ENKELE_REIS'
    OVCHIPKAART_RETOUR = 'OVCHIPKAART_RETOUR'
    TRAJECT_VRIJ_JAAR = 'TRAJECT_VRIJ_JAAR'
    BUSINESS_CARD_TRAJECT_VRIJ_JAAR = 'BUSINESS_CARD_TRAJECT_VRIJ_JAAR'
    RAILRUNNER = 'RAILRUNNER'
    ETICKET_ENKELE_REIS = 'ETICKET_ENKELE_REIS'
    ETICKET_RETOUR = 'ETICKET_RETOUR'


class Price(BaseModel):
    operatorName: str | None = None
    priceDifferenceInCentsBetweenFirstAndSecondClass: int | None = None
    priceDifferenceInCentsBetweenJointJourneyDiscount: int | None = None
    totalPriceInCents: int
    travelClass: TravelClass
    travelDiscount: TravelDiscount
    travelProducts: list[TravelProduct]


class DiscountType(Enum):
    NONE = 'NONE'
    EARLY_BOOKING = 'EARLY_BOOKING'
    GROUP = 'GROUP'
    JOINT_JOURNEY = 'JOINT_JOURNEY'
    RAILRUNNER = 'RAILRUNNER'
    NS_DEAL = 'NS_DEAL'


class Type5(Enum):
    TRIP_CANCELLED = 'TRIP_CANCELLED'
    LEG_CANCELLED = 'LEG_CANCELLED'
    LEG_TRANSFER_IMPOSSIBLE = 'LEG_TRANSFER_IMPOSSIBLE'
    ALTERNATIVE_TRANSPORT = 'ALTERNATIVE_TRANSPORT'
    DISRUPTION = 'DISRUPTION'
    MAINTENANCE = 'MAINTENANCE'
    REPLACEMENT = 'REPLACEMENT'
    ADDITIONAL = 'ADDITIONAL'
    SHORTENED_TRAIN = 'SHORTENED_TRAIN'


class Type6(Enum):
    TRAIN = 'TRAIN'
    BUS = 'BUS'
    TRAM = 'TRAM'
    METRO = 'METRO'
    FERRY = 'FERRY'
    WALK = 'WALK'
    BIKE = 'BIKE'
    CAR = 'CAR'
    TAXI = 'TAXI'
    SHARED_MODALITY = 'SHARED_MODALITY'
    UNKNOWN = 'UNKNOWN'


class RegistrationAvailability(BaseModel):
    bicycle: bool
    numberOfBicyclePlaces: int | None = None
    numberOfSeats: int | None = None
    seats: bool


class RepresentationResponsePrice(BaseModel):
    links: dict[str, Link] | None = None
    meta: dict[str, dict[str, Any]] | None = None
    payload: Price


class RouteStation(BaseModel):
    mediumName: str | None = None
    uicCode: str | None = None


class Type7(Enum):
    NS_DEAL_DISCOUNT = 'NS_DEAL_DISCOUNT'


class SalesOption(BaseModel):
    betterOption: bool
    labelText: str | None = None
    originalPrice: int | None = None
    permilleFullTariff: int | None = None
    priceInCents: int | None = None
    recommendationText: str | None = None
    type: Type7


class ServiceBookingInfo(BaseModel):
    canChangeAssistance: bool
    defaultAssistanceValue: bool
    message: str | None = None
    name: str
    serviceTypeIds: list[str]
    stationUic: str | None = None
    tripLegIndex: str


class NearByMeMapping(Enum):
    OV_FIETS = 'OV_FIETS'
    SHARED_ELECTRICAL_BIKE = 'SHARED_ELECTRICAL_BIKE'
    SHARED_BIKE = 'SHARED_BIKE'
    SHARED_SCOOTER = 'SHARED_SCOOTER'
    SHARED_CAR = 'SHARED_CAR'
    UNKNOWN = 'UNKNOWN'


class SharedModality(BaseModel):
    availability: bool
    name: str | None = None
    nearByMeMapping: NearByMeMapping
    planIcon: str | None = None
    provider: str


class StationsNamen(BaseModel):
    festive: str | None = None
    kort: str
    lang: str
    middel: str


class StockPartLink(BaseModel):
    uri: str


class Type8(Enum):
    U = 'U'
    A = 'A'
    I = 'I'
    R = 'R'
    H = 'H'


class StopNote(BaseModel):
    key: str | None = None
    priority: int | None = None
    type: Type8
    value: str


class Styles(BaseModel):
    type: str


class Type9(Enum):
    RESERVATION = 'RESERVATION'
    SUPPLEMENT = 'SUPPLEMENT'
    SPECIAL_TICKET = 'SPECIAL_TICKET'


class TicketAction(BaseModel):
    fromUicCode: str | None = None
    toUicCode: str | None = None
    type: Type9


class Track(BaseModel):
    spoorNummer: str


class Type10(Enum):
    IMPOSSIBLE_TRANSFER = 'IMPOSSIBLE_TRANSFER'
    SPECIAL = 'SPECIAL'
    CHECKOVER_INSTRUCTION = 'CHECKOVER_INSTRUCTION'
    CROSS_PLATFORM = 'CROSS_PLATFORM'
    TRANSFER_TIME = 'TRANSFER_TIME'


class Source(Enum):
    HARP = 'HARP'
    NEGENTWEE = 'NEGENTWEE'
    GOOGLE = 'GOOGLE'
    PAS = 'PAS'


class TravelAssistanceInfo(BaseModel):
    isAssistanceRequired: bool
    termsAndConditionsLink: str | None = None
    tripRequestId: int


class Status2(Enum):
    CANCELLED = 'CANCELLED'
    CHANGE_NOT_POSSIBLE = 'CHANGE_NOT_POSSIBLE'
    ALTERNATIVE_TRANSPORT = 'ALTERNATIVE_TRANSPORT'
    DISRUPTION = 'DISRUPTION'
    MAINTENANCE = 'MAINTENANCE'
    UNCERTAIN = 'UNCERTAIN'
    REPLACEMENT = 'REPLACEMENT'
    ADDITIONAL = 'ADDITIONAL'
    SPECIAL = 'SPECIAL'
    NORMAL = 'NORMAL'


class Type11(Enum):
    NS = 'NS'
    NS_ACCESSIBLE = 'NS_ACCESSIBLE'
    NEGENTWEE = 'NEGENTWEE'
    GOOGLE = 'GOOGLE'
    PAS = 'PAS'


class SupplementType(Enum):
    ICD = 'ICD'
    ICE = 'ICE'


class TripFareSupplement(BaseModel):
    fromUICCode: str | None = None
    link: Link | None = None
    supplementPriceInCents: int
    supplementType: SupplementType | None = None
    toUICCode: str | None = None


class CheckinStatus(Enum):
    CHECKIN = 'CHECKIN'
    CHECKOUT = 'CHECKOUT'
    OVERCHECK = 'OVERCHECK'
    DETOUR = 'DETOUR'
    REQUIRED_CHECK_OUT_IN = 'REQUIRED_CHECK_OUT_IN'
    NOTHING = 'NOTHING'


class ExitSide(Enum):
    LEFT = 'LEFT'
    RIGHT = 'RIGHT'
    UNKNOWN = 'UNKNOWN'


class Type12(Enum):
    STATION = 'STATION'
    ADDRESS = 'ADDRESS'
    POINT_OF_INTEREST = 'POINT_OF_INTEREST'


class DiscountType1(Enum):
    NO_DISCOUNT = 'NO_DISCOUNT'
    DISCOUNT_20_PERCENT = 'DISCOUNT_20_PERCENT'
    DISCOUNT_40_PERCENT = 'DISCOUNT_40_PERCENT'
    NO_CHARGE = 'NO_CHARGE'
    OTHER = 'OTHER'


class Product1(Enum):
    OVCHIPKAART_ENKELE_REIS = 'OVCHIPKAART_ENKELE_REIS'
    OVCHIPKAART_RETOUR = 'OVCHIPKAART_RETOUR'
    TRAJECT_VRIJ_JAAR = 'TRAJECT_VRIJ_JAAR'
    BUSINESS_CARD_TRAJECT_VRIJ_JAAR = 'BUSINESS_CARD_TRAJECT_VRIJ_JAAR'
    ETICKET_ENKELE_REIS = 'ETICKET_ENKELE_REIS'
    ETICKET_RETOUR = 'ETICKET_RETOUR'
    NS_DEAL_DISCOUNT_ENKELE_REIS = 'NS_DEAL_DISCOUNT_ENKELE_REIS'
    RAILRUNNER = 'RAILRUNNER'
    ICE_SUPPLEMENT = 'ICE_SUPPLEMENT'
    ICD_SUPPLEMENT = 'ICD_SUPPLEMENT'
    NSI = 'NSI'


class TripSalesFare(BaseModel):
    discountType: DiscountType1 | None = None
    link: str | None = None
    priceInCents: int | None = None
    priceInCentsExcludingSupplement: int | None = None
    product: Product1 | None = None
    supplementInCents: int | None = None
    travelClass: TravelClass | None = None


class Product2(Enum):
    GEEN = 'GEEN'
    OVCHIPKAART_ENKELE_REIS = 'OVCHIPKAART_ENKELE_REIS'
    OVCHIPKAART_RETOUR = 'OVCHIPKAART_RETOUR'
    DAL_VOORDEEL = 'DAL_VOORDEEL'
    ALTIJD_VOORDEEL = 'ALTIJD_VOORDEEL'
    DAL_VRIJ = 'DAL_VRIJ'
    WEEKEND_VRIJ = 'WEEKEND_VRIJ'
    ALTIJD_VRIJ = 'ALTIJD_VRIJ'
    BUSINESSCARD = 'BUSINESSCARD'
    BUSINESSCARD_DAL = 'BUSINESSCARD_DAL'
    STUDENT_WEEK = 'STUDENT_WEEK'
    STUDENT_WEEKEND = 'STUDENT_WEEKEND'
    VDU = 'VDU'
    SAMENREISKORTING = 'SAMENREISKORTING'
    TRAJECT_VRIJ = 'TRAJECT_VRIJ'


class TripTravelFare(BaseModel):
    buyableTicketPriceInCents: int | None = None
    buyableTicketPriceInCentsExcludingSupplement: int | None = None
    buyableTicketSupplementPriceInCents: int | None = None
    discountType: DiscountType1
    link: str | None = None
    priceInCents: int | None = None
    priceInCentsExcludingSupplement: int | None = None
    product: Product2 | None = None
    supplementInCents: int | None = None
    travelClass: TravelClass | None = None


class Unit(BaseModel):
    pass


class ApiV2DeparturesGetParameters(BaseModel):
    lang: str | None = None
    station: str | None = None
    uicCode: str | None = None
    dateTime: AwareDatetime | None = None
    maxJourneys: int | None = None


class ApiV2ArrivalsGetParameters(BaseModel):
    lang: str | None = None
    station: str | None = None
    uicCode: str | None = None
    dateTime: AwareDatetime | None = None
    maxJourneys: int | None = None


class ApiV2JourneyGetParameters(BaseModel):
    train: int | None = None
    id: str | None = None
    dateTime: AwareDatetime | None = None
    departureUicCode: str | None = None
    transferUicCode: str | None = None
    arrivalUicCode: str | None = None
    omitCrowdForecast: bool | None = False


class TravelRequestType(Enum):
    DEFAULT = 'DEFAULT'
    DIRECTIONS = 'DIRECTIONS'
    DIRECTIONS_ONLY = 'DIRECTIONS_ONLY'


class ApiV3TripsTripGetParameters(BaseModel):
    ctxRecon: str
    date: AwareDatetime | None = None
    travelRequestType: TravelRequestType | None = 'DEFAULT'
    sourceCtxRecon: bool | None = False
    nsr: int | None = None
    product: Product2 | None = None
    discount: str | None = 'NO_DISCOUNT'
    travelClass: int | None = 2


class ApiV1CalamitiesGetParameters(BaseModel):
    lang: str | None = None


class TravelType1(Enum):
    single = 'single'
    return_ = 'return'


class ApiV3PriceGetParameters(BaseModel):
    fromStation: str | None = None
    toStation: str | None = None
    travelClass: TravelClass | None = None
    travelType: TravelType1 | None = None
    isJointJourney: bool | None = False
    adults: int | None = 1
    children: int | None = 0
    routeId: str | None = None
    plannedDepartureTime: AwareDatetime | None = None
    plannedArrivalTime: AwareDatetime | None = None


class ApiV2StationsGetParameters(BaseModel):
    q: constr(min_length=2, max_length=2147483647) | None = None
    countryCodes: list[str] | None = None
    limit: int | None = 10


class ApiV3TripsGetParameters(BaseModel):
    lang: str | None = None
    fromStation: str | None = None
    originUicCode: str | None = None
    originLat: float | None = None
    originLng: float | None = None
    originName: str | None = None
    toStation: str | None = None
    destinationUicCode: str | None = None
    destinationLat: float | None = None
    destinationLng: float | None = None
    destinationName: str | None = None
    viaStation: str | None = None
    viaUicCode: str | None = None
    viaLat: float | None = None
    viaLng: float | None = None
    originWalk: bool | None = False
    originBike: bool | None = False
    originCar: bool | None = False
    destinationWalk: bool | None = False
    destinationBike: bool | None = False
    destinationCar: bool | None = False
    dateTime: AwareDatetime | None = None
    searchForArrival: bool | None = None
    departure: bool | None = None
    context: str | None = None
    shorterChange: bool | None = False
    addChangeTime: int | None = None
    minimalChangeTime: int | None = None
    viaWaitTime: int | None = None
    originAccessible: bool | None = None
    travelAssistance: bool | None = False
    nsr: int | None = None
    travelAssistanceTransferTime: int | None = None
    accessibilityEquipment1: str | None = None
    accessibilityEquipment2: str | None = None
    searchForAccessibleTrip: bool | None = False
    filterTransportMode: str | None = None
    localTrainsOnly: bool | None = False
    excludeHighSpeedTrains: bool | None = False
    excludeTrainsWithReservationRequired: bool | None = False
    product: Product2 | None = None
    discount: str | None = 'NO_DISCOUNT'
    travelClass: int | None = 2
    passing: bool | None = False
    travelRequestType: TravelRequestType | None = 'DEFAULT'
    disabledTransportModalities: list[str] | None = None
    firstMileModality: str | None = None
    lastMileModality: str | None = None
    entireTripModality: str | None = None


class ApiV3DisruptionsStationStationCodeGetParameters(BaseModel):
    stationCode: str


class ApiV3DisruptionsStationStationCodeGetResponse(RootModel[list[BaseDisruption]]):
    root: list[BaseDisruption]


class Type13(Enum):
    CALAMITY = 'CALAMITY'
    DISRUPTION = 'DISRUPTION'
    MAINTENANCE = 'MAINTENANCE'


class ApiV3DisruptionsTypeIdGetParameters(BaseModel):
    type: Type13
    id: str


class TypeEnum(Enum):
    CALAMITY = 'CALAMITY'
    DISRUPTION = 'DISRUPTION'
    MAINTENANCE = 'MAINTENANCE'


class ApiV3DisruptionsGetParameters(BaseModel):
    type: list[TypeEnum] | None = None
    isActive: bool | None = False


class ApiV3DisruptionsGetResponse(RootModel[list[BaseDisruption]]):
    root: list[BaseDisruption]


class TravelClass5(Enum):
    field_1 = '1'
    field_2 = '2'


class ApiV2PriceGetParameters(BaseModel):
    fromStation: str | None = None
    toStation: str | None = None
    travelClass: TravelClass5 | None = None
    travelType: TravelType1 | None = None
    isJointJourney: bool | None = False
    adults: int | None = 1
    children: int | None = 0
    routeId: str | None = None
    plannedFromTime: AwareDatetime | None = None
    plannedArrivalTime: AwareDatetime | None = None


class ApiV2StationsNearestGetParameters(BaseModel):
    lat: float
    lng: float
    limit: int | None = 2


class ApiV3TripsBookedTripGetParameters(BaseModel):
    ctxRecon: str
    bookingNumber: int
    originalTripRequestId: int
    accessibilityEquipment1: str | None = None
    accessibilityEquipment2: str | None = None


class APIError(BaseModel):
    code: int
    errors: list[LocalizedErrorDetail] | None = None
    exception: str | None = None
    message: str
    path: str
    requestId: str
    timestamp: AwareDatetime


class Download(BaseModel):
    bestand: DownloadFile | None = None
    titel: str | None = None


class JourneyDetailLink(BaseModel):
    link: Link
    type: Type3


class JourneyRegistrationParameters(BaseModel):
    availability: RegistrationAvailability | None = None
    bicycleReservationRequired: bool
    searchUrl: AnyUrl
    status: Status
    url: AnyUrl | None = None


class NesLine(BaseModel):
    color: str
    styles: NesLineStyles | None = None


class NesProperties(BaseModel):
    color: str
    icon: str | None = None
    scope: Scope | None = None
    styles: Styles | None = None
    type: str | None = None


class NesText(BaseModel):
    accessibilityText: str
    backgroundColor: str | None = None
    color: str
    styles: NesTextStyles | None = None
    text: str


class Note(BaseModel):
    accessibilityValue: str | None = None
    category: Category | None = None
    isPresentationRequired: bool = True
    key: str | None = None
    link: Link | None = None
    nesProperties: NesProperties | None = None
    noteType: NoteType | None = None
    priority: int | None = None
    routeIdxFrom: int | None = None
    routeIdxTo: int | None = None
    shortValue: str | None = None
    value: str | None = None


class PriceV3(BaseModel):
    conditionsHeader: str = Field(..., description='Header of conditions')
    conditionsText: str | None = Field(None, description='Conditions of product')
    conditionsUrl: str | None = Field(
        None, description='Url to webpage with common conditions'
    )
    discountInCents: int | None = Field(
        None, description='Discount price compared to total price without any discount'
    )
    discountType: DiscountType = Field(..., description='Type of discount')
    displayName: str = Field(..., description='Display name of product')
    isBestOption: bool = Field(
        ..., description='Indicates if this price is the best option for client'
    )
    isSelectable: bool = Field(
        ..., description='Denotes if the user can select this option'
    )
    operatorName: str | None = Field(None, description='Name of the operator')
    pricePerAdultInCents: int = Field(..., description='Price per adult')
    pricePerChildInCents: int = Field(..., description='Price per child')
    productId: str = Field(..., description='Product ID used to buy ticket')
    totalPriceInCents: int = Field(..., description='Total price')
    travelClass: TravelClass = Field(..., description='Traveling class')
    travelProducts: list[Unit] = Field(..., description='Travel products types')


class PricesResponseV3(BaseModel):
    prices: list[PriceV3]


class ProductInterface(BaseModel):
    categoryCode: str | None = None
    displayName: str | None = None
    iconNesProperties: NesProperties | None = None
    longCategoryName: str | None = None
    nameNesProperties: NesProperties | None = None#NesProperties
    notes: list[list[Note]] | None = None#list[list[Note]]
    number: str | None = None
    operatorAdministrativeCode: int | None = None
    operatorCode: str | None = None
    operatorName: str | None = None
    productType: str | None = None#str
    shortCategoryName: str | None = None
    type: Type6


class RepresentationResponsePricesResponseV3(BaseModel):
    links: dict[str, Link] | None = None
    meta: dict[str, dict[str, Any]] | None = None
    payload: PricesResponseV3


class Station(BaseModel):
    EVACode: str | None = None
    UICCdCode: str | None = None
    UICCode: str
    cdCode: int | None = None
    code: str | None = None
    distance: float | None = None
    eindDatum: date_aliased | None = None
    heeftFaciliteiten: bool
    heeftReisassistentie: bool
    heeftVertrektijden: bool
    ingangsDatum: date_aliased | None = None
    land: str | None = None
    lat: float | None = None
    lng: float | None = None
    naderenRadius: int | None = None
    namen: StationsNamen | None = None
    nearbyMeLocationId: NearbyMeLocationId | None = None
    radius: int | None = None
    sporen: list[Track]
    stationType: str
    synoniemen: list[str]


class StationResponse(BaseModel):
    links: dict[str, str] | None = None
    meta: dict[str, str] | None = None
    payload: list[Station]


class Step(BaseModel):
    duration: NesText | None = None
    icon: NesIcon | None = None
    line: NesLine
    text: NesText


class Stop(BaseModel):
    actualArrivalDateTime: AwareDatetime | None = None
    actualArrivalTimeZoneOffset: int | None = None
    actualArrivalTrack: str | None = None
    actualDepartureDateTime: AwareDatetime | None = None
    actualDepartureTimeZoneOffset: int | None = None
    actualDepartureTrack: str | None = None
    actualPassingDateTime: AwareDatetime | None = None
    arrivalDelayInSeconds: int | None = None
    arrivalPrognosisType: str | None = None
    borderStop: bool
    cancelled: bool
    countryCode: str | None = None
    departureDelayInSeconds: int | None = None
    departurePrognosisType: str | None = None
    lat: float | None = None
    lng: float | None = None
    name: str | None = None
    notes: list[StopNote]
    passing: bool
    plannedArrivalDateTime: AwareDatetime | None = None
    plannedArrivalTimeZoneOffset: int | None = None
    plannedArrivalTrack: str | None = None
    plannedDepartureDateTime: AwareDatetime | None = None
    plannedDepartureTimeZoneOffset: int | None = None
    plannedDepartureTrack: str | None = None
    plannedPassingDateTime: AwareDatetime | None = None
    quayCode: str | None = None
    routeIdx: int | None = None
    uicCdCode: str | None = None
    uicCode: str | None = None


class TransferMessage(BaseModel):
    accessibilityMessage: str
    iconNesProperties: NesProperties | None = None
    message: str
    messageNesProperties: NesProperties
    type: Type10


class TravelAdviceMessage(BaseModel):
    disruptionIds: list[str]
    nesProperties: NesProperties
    title: str


class TripFareOptions(BaseModel):
    isEticketBuyable: bool
    isInternational: bool
    isInternationalBookable: bool
    isPossibleWithOvChipkaart: bool
    isTotalPriceUnknown: bool
    reasonEticketNotBuyable: EticketNotBuyableReason | None = None
    salesOptions: list[SalesOption] | None = None
    supplementsBasedOnSelectedFare: list[TripFareSupplement] | None = None


class TripOriginDestination(BaseModel):
    actualDateTime: AwareDatetime | None = None
    actualTimeZoneOffset: int | None = None
    actualTrack: str | None = None
    checkinStatus: CheckinStatus | None = None
    city: str | None = None
    countryCode: str | None = None
    exitSide: ExitSide | None = None
    lat: float | None = None
    lng: float | None = None
    name: str | None = None
    notes: list[Note] | None = None
    plannedDateTime: AwareDatetime | None = None
    plannedTimeZoneOffset: int | None = None
    plannedTrack: str | None = None
    prognosisType: str | None = None
    quayCode: str | None = None
    rawLocationName: str | None = Field(
        None,
        description='The raw location name is the same as the name, except it excluded prefixes such as bushalte/metrohalte/etc. and it excludes emojis',
    )
    stationCode: str | None = None
    travelAssistanceBookingInfo: ServiceBookingInfo | None = None
    travelAssistanceMeetingPointDetails: list[MeetingPointDetails] | None = None
    travelAssistanceMeetingPoints: list[str] | None = None
    type: Type12 | None = None
    uicCdCode: str | None = None
    uicCode: str | None = None


class CalamityBodyItem(BaseModel):
    content: str | None = None
    downloads: list[Download] | None = None
    links: list[Link] | None = None
    objectType: str
    titel: str | None = None


class Duration(BaseModel):
    accessibilityValue: str
    nesProperties: NesProperties
    value: str


class FareLeg(BaseModel):
    destination: TripOriginDestination
    fares: list[TripTravelFare]
    operator: str | None = None
    origin: TripOriginDestination
    productTypes: list[ProductType]
    travelDate: date_aliased | None = None


class Message(BaseModel):
    endDate: str | None = None
    endTime: str | None = None
    externalId: str | None = None
    head: str | None = None
    id: str | None = None
    lead: str | None = None
    nesProperties: NesProperties | None = None
    phase: Phase | None = None
    routeIdxFrom: int | None = None
    routeIdxTo: int | None = None
    startDate: str | None = None
    startTime: str | None = None
    text: str | None = None
    type: Type4 | None = None


class ModalityListItem(BaseModel):
    accessibilityName: str
    actualTrack: str | None = None
    iconNesProperties: NesProperties | None = None
    name: str
    nameNesProperties: NesProperties


class Part(BaseModel):
    destination: TripOriginDestination | None = None#Station | None = None
    facilities: list[str]
    image: StockPartLink | None = None
    stockIdentifier: str | None = None


class PrimaryMessage(BaseModel):
    message: Message | None = None
    nesProperties: NesProperties
    title: str
    type: Type5


class Product(ProductInterface):
    nesProperties: NesProperties | None = None
    notes: list[list[Note]] = Field(
        ...,
        description='notes is a List of Lists because this allows frontend clients to render the elements of every nested List on the same row',
    )
    nameNesProperties: NesProperties
    type: Type6
    productType: Literal['Product']


class Stock(BaseModel):
    hasSignificantChange: bool
    numberOfParts: int
    numberOfSeats: int
    trainParts: list[Part]
    trainType: str | None = None


class Arrival(BaseModel):
    actualDateTime: AwareDatetime | None = None
    actualTimeZoneOffset: int | None = None
    actualTrack: str | None = None
    arrivalStatus: ArrivalStatus
    cancelled: bool
    journeyDetailRef: str | None = None
    messages: list[Message]
    name: str
    origin: str | None = None
    plannedDateTime: AwareDatetime | None = None
    plannedTimeZoneOffset: int | None = None
    plannedTrack: str | None = None
    product: Product
    trainCategory: str


class ArrivalOrDeparture(BaseModel):
    actualTime: AwareDatetime | None = None
    actualTrack: str | None = None
    cancelled: bool
    crowdForecast: CrowdForecast
    delayInSeconds: int | None = None
    destination: TripOriginDestination | None = None#Station | None = None
    origin: TripOriginDestination | None = None#Station | None = None
    plannedTime: AwareDatetime | None = None
    plannedTrack: str | None = None
    product: ProductInterface#Product
    punctuality: float | None = None
    shorterStockClassification: ShorterStockClassification | None = None
    stockIdentifiers: list[str] | None = None


class ArrivalsPayload(BaseModel):
    arrivals: list[Arrival]
    source: str


class CalamitiesResourceCalamity(BaseModel):
    beschrijving: str | None = None
    bodyitems: list[CalamityBodyItem] | None = None
    buttonPositie: ButtonPositie | None = None
    calltoactionbuttons: list[CallToActionButton] | None = None
    id: str | None = None
    laatstGewijzigd: int | None = None
    lastModified: int | None = None
    titel: str | None = None
    type: Type1 | None = None
    url: str | None = None
    volgendeUpdate: int | None = None


class CalamitiesResponse(BaseModel):
    calamiteit: CalamitiesResourceCalamity | None = None
    meldingen: list[CalamitiesResourceCalamity] | None = None


class Departure(BaseModel):
    actualDateTime: AwareDatetime | None = None
    actualTimeZoneOffset: int | None = None
    actualTrack: str | None = None
    cancelled: bool
    departureStatus: DepartureStatus
    direction: str | None = None
    journeyDetailRef: str | None = None
    messages: list[Message]
    name: str
    plannedDateTime: AwareDatetime | None = None
    plannedTimeZoneOffset: int | None = None
    plannedTrack: str | None = None
    product: Product
    routeStations: list[RouteStation]
    trainCategory: str


class DeparturesPayload(BaseModel):
    departures: list[Departure]
    source: str


class JourneyStop(BaseModel):
    actualStock: Stock | None = None
    arrivals: list[ArrivalOrDeparture]
    coachCrowdForecast: list[CoachCrowdForecast] | None = None
    departures: list[ArrivalOrDeparture]
    destination: str | None = None
    id: str
    kind: Kind | None = None
    nextStopId: list[str]
    plannedStock: Stock | None = None
    platformFeatures: list[PlatformFeature] | None = None
    previousStopId: list[str]
    status: Status1 | None = None
    stop: TripOriginDestination#Station


class Leg(BaseModel):
    actualDurationInMinutes: int | None = None
    alternativeTransport: bool
    bicycleSpotCount: int | None = None
    cancelled: bool
    changeCouldBePossible: bool | None = None
    changePossible: bool
    checkinStep: CheckinStep | None = None
    coordinates: list[list[float]] | None = None
    crossPlatformTransfer: bool | None = None
    crowdForecast: CrowdForecast | None = None
    destination: TripOriginDestination
    direction: str | None = None
    distanceInMeters: int | None = None
    duration: Duration | None = None
    idx: str | None = None
    isAfterCancelledLeg: bool
    isOnOrAfterCancelledLeg: bool
    journeyDetail: list[JourneyDetailLink] | None = None
    journeyDetailRef: str | None = None
    messages: list[Message] | None = None
    minimallyAddedChangeTime: int | None = None
    name: str | None = None
    nesProperties: NesProperties | None = None
    notes: list[Note] | None = None
    origin: TripOriginDestination
    overviewPolyLine: list[Coordinate] | None = None
    partCancelled: bool
    plannedDurationInMinutes: int | None = None
    postSteps: list[Step]
    preSteps: list[Step]
    product: Product | None = Field(None, discriminator='productType')
    punctuality: float | None = None
    reachable: bool
    recognizableDestination: str | None = None
    sharedModality: SharedModality | None = None
    shorterStock: bool | None = None
    shorterStockClassification: ShorterStockClassification | None = None
    shorterStockWarning: str | None = None
    steps: list[Step] | None = None
    stops: list[Stop]
    ticketActions: list[TicketAction] | None = None
    transferMessages: list[TransferMessage] | None = None
    transferTimeToNextLeg: int | None = None
    travelAssistanceArrival: ServiceBookingInfo | None = None
    travelAssistanceDeparture: ServiceBookingInfo | None = None
    travelType: TravelType | None = None


class RepresentationResponseArrivalsPayload(BaseModel):
    links: dict[str, Link] | None = None
    meta: dict[str, dict[str, Any]] | None = None
    payload: ArrivalsPayload


class RepresentationResponseDeparturesPayload(BaseModel):
    links: dict[str, Link] | None = None
    meta: dict[str, dict[str, Any]] | None = None
    payload: DeparturesPayload


class Trip(BaseModel):
    actualDurationInMinutes: int | None = Field(
        None,
        description='Actual duration of this trip in minutes, or the planned duration if no realtime information about this trip is available.',
    )
    bookingUrl: Link | None = None
    crowdForecast: CrowdForecast | None = None
    ctxRecon: str = Field(
        ...,
        description='Reconstruction context for this trip. Can be used to reconstruct this exact trip with the v3/trips/trip endpoint',
    )
    eco: Eco | None = None
    fareLegs: list[FareLeg] | None = None
    fareOptions: TripFareOptions | None = None
    fareRoute: FareRoute | None = None
    fares: list[TripSalesFare] | None = None
    labelListItems: list[LabelListItem] | None = None
    legs: list[Leg]
    messages: list[Message] | None = Field(
        None,
        description='List of messages regarding maintenance or disruption that influences this trip.',
    )
    modalityListItems: list[ModalityListItem] | None = None
    nsiLink: NsiLink | None = None
    optimal: bool = Field(
        ...,
        description='Whether or not this trip is regarded the best possible option of all returned trips',
    )
    overviewPolyLine: list[Coordinate] | None = None
    plannedDurationInMinutes: int | None = Field(
        None, description='Planned duration of this trip in minutes'
    )
    primaryMessage: PrimaryMessage | None = None
    productFare: TripTravelFare | None = None
    punctuality: float | None = None
    realtime: bool
    registerJourney: JourneyRegistrationParameters | None = None
    routeId: str | None = None
    shareUrl: Link | None = None
    sourceCtxRecon: str | None = Field(
        None,
        description="Reconstruction context for this trip set by the travel advice source system. Can be used to interact follow-up requests with the source system, like booking a trip with travel assistance (NSRA). Can be null if the source doesn't provide a ctxRecon",
    )
    status: Status2 = Field(..., description='Status of this trip')
    transfers: int = Field(..., description='Number of public transit transfers')
    travelAssistanceInfo: TravelAssistanceInfo | None = None
    type: Type11
    uid: str = Field(..., description='Unique identifier for this trip')


class Journey(BaseModel):
    allowCrowdReporting: bool
    notes: list[Note]
    productNumbers: list[str]
    source: str
    stops: list[JourneyStop]


class RepresentationResponseJourney(BaseModel):
    links: dict[str, Link] | None = None
    meta: dict[str, dict[str, Any]] | None = None
    payload: Journey


class TravelAdvice(BaseModel):
    message: str | None = Field(
        None, description='Optional message indicating why the list of trips is empty.'
    )
    scrollRequestBackwardContext: str | None = Field(
        None,
        description='Scroll context to use when scrolling back in time. Can be used in scrollContext query parameter',
    )
    scrollRequestForwardContext: str | None = Field(
        None,
        description='Scroll context to use when scrolling forward in time. Can be used in scrollContext query parameter',
    )
    source: Source = Field(
        ..., description='Source system that has generated these travel advices'
    )
    travelAdviceMessage: TravelAdviceMessage | None = None
    trips: list[Trip] = Field(..., description='List of trips')


class ApiV3TripsGetResponse(RootModel[list[TravelAdvice]]):
    root: list[TravelAdvice]
