schema:
  - "types.graphqls"
  - "base.graphqls"
  - "passService.graphqls"
  - "place.graphqls"
  - "stop.graphqls"
  - "findJourneys.graphqls"
extensions:
  endpoints:
    # Allows us to use IntelliJ scratch files to query the server
    # when running it on localhost
    default: http://localhost:8080/graphql
